spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    password: ${database.password}
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:granitis_db;DATABASE_TO_LOWER=TRUE
    username: granitis_app
  h2:
    console.enabled: true
  liquibase:
    enabled: true
    change-log: db.changelog.xml