server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: 'health,info'

springdoc:
  swagger-ui:
    disable-swagger-default-url: 'true'
    path: '/swagger-ui'

spring:
  datasource:
    password: ${database.password}
    driver-class-name: org.h2.Driver
#    jdbcUrl: jdbc:postgresql://${database.host}/arachni
    url: jdbc:h2:mem:granitis_db
    username: granitis_app
  h2:
    console.enabled: true
  liquibase:
    enabled: 'false'